config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'
  resources :questions

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/question.rb
class Question < ApplicationRecord
  validates :title, presence: true, length: {minimum: 2}
  validates :body, presence: true, length: {minimum: 2}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
@name = params[:name]
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def destroy
    @question = Question.find_by id: params[:id]
    @question.destroy
    redirect_to questions_path
  end

  def index
    @questions = Question.all
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new question_params
    if @question.save
      redirect_to questions_path
    else
      render :new
    end
  end

  def edit
    @question = Question.find_by id: params[:id]
  end

  def update
    @question = Question.find_by id: params[:id]
    if @question.update question_params
      redirect_to questions_path
    else
      render :edit
    end
  end

  def show
    @question = Question.find_by id: params[:id]
  end


  private
  def question_params
    params.require(:question).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Askit</title>

  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">
  <%= stylesheet_link_tag "application", media: 'all', "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
</head>

<body>
<div class="header">
  <div class="container">
    <div class="header-logo">
      <h1 class="header-title"><%= link_to "Хорошие вопросы", root_path %></h1>
    </div>
    <div class="header-nav">
      <%= link_to 'Home', root_path, class: 'button button-light button-small' %>
      <%= link_to 'Questions', questions_path, class: 'button button-light button-small' %>
      <%= link_to 'New Questions', new_question_path, class: 'button button-light button-small' %>
    </div>
  </div>
</div>
<div class="content">
  <div class="container">
    <%= yield %>
  </div>
</div>
</body>
</html>

app/views/pages/index.html.erb
<div class="container content-wrapper buffer-both">
  <h1 class="title-medium">Welcome to AskIt!</h1>

  &copy; @kasukhin <%= Time.now.year %>
</div>

app/views/questions/_form.html.erb
<%= form_with model: @question do |f| %>
  <div class="mb-3 row">
    <%= f.label :title, class: 'col-sm-2 col-form-label'%>
    <%= f.text_field :title, required: true, minlength: 2, placeholder: "Title", class: 'form-control' %>
  </div>

  <div class="form-field">
    <%= f.label :body, class: 'form-label' %>
    <%= f.text_area :body, required: true, minlength: 2, class: 'form-textarea' %>
  </div>

  <%= f.submit "Submit question!", class: 'button button-dark button-small' %>
<% end %>

app/views/questions/edit.html.erb
<div class="container content-wrapper buffer-both">
  <h1 class="title-medium">Edit Question</h1>

<%= render "form" %>
</div>

app/views/questions/index.html.erb
<div class="container content-wrapper buffer-both">
  <h1 class="title-medium">Questions</h1>
    <div class="question-content">

  <% @questions.each do |question| %>
    <h2><%= question.title %></h2>

        <div class="question-date">
    <time datetime="<%= question.created_at.strftime('%Y-%m-%d %H:%M:%S') %>">
      <%= question.created_at.strftime('%Y-%m-%d %H:%M:%S') %></time>
        </div>
        <div class="question-text text-lead">
   <%= question.body %>
        </div>

    <%= link_to 'Edit', edit_question_path(question), class: 'button button-dark button-small' %>
    <%= link_to 'Show', question_path(question), class: 'button button-dark button-small' %>
    <%= link_to 'Destroy', question_path(question), data: { turbo_method: :delete, turbo_confirm: 'Вы уверены?' }, class: 'button button-dark button-small' %>

  <% end %>
</div>
  </div>>

app/views/questions/new.html.erb
<div class="container content-wrapper buffer-both">
  <h1 class="title-medium">New Question</h1>

  <%= render "form" %>
</div>

app/views/questions/show.html.erb
<div class="container content-wrapper buffer-both">
  <h1 class="title-medium"><%= @question.title %></h1>

  <p>
    <time datetime="<%= @question.created_at.strftime('%Y-%m-%d %H:%M:%S') %>">
      <%= @question.created_at.strftime('%Y-%m-%d %H:%M:%S') %></time>
    <br>
    <%= @question.body %>
  </p>
</div>